use super::AnalysisResult;
use crate::analysis::FunctionMetric;
use crate::scoring::Score;
use std::collections::HashMap;
use std::fmt::Write;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};

pub fn generate_markdown_report(res: &AnalysisResult, root_dir: &Path) -> io::Result<PathBuf> {
    let out_dir = root_dir.join("tools").join("cargo-sig");
    if !out_dir.exists() {
        fs::create_dir_all(&out_dir)?;
    }
    let report_path = out_dir.join("SIG_REPORT.md");
    let content = render_markdown(res, root_dir);
    fs::write(&report_path, content)?;
    Ok(report_path)
}

#[must_use]
pub fn render_markdown(res: &AnalysisResult, root_dir: &Path) -> String {
    let mut out = String::with_capacity(8192);

    out.push_str("# 📊 SIG Maintainability Report\n\n");
    out.push_str("> Generated by [cargo-sig](https://github.com/Vicente-Alejandro/Cargo-Software-Improvement-Group-Analyzer) — Local Software Improvement Group static analysis.\n\n");

    render_summary_section(&mut out, res.score);
    render_violations_section(&mut out, res, root_dir);
    render_hotspots_section(&mut out, res, root_dir);
    render_architecture_section(&mut out, res, root_dir);

    out
}

fn render_summary_section(out: &mut String, s: &Score) {
    out.push_str("## 🎯 Maintainability Scorecard\n\n");
    out.push_str("| Metric | Rating | Details |\n");
    out.push_str("| :--- | :---: | :--- |\n");

    let final_stars = star_icons(s.stars);
    let code_stars = star_icons(s.code_stars);
    let vol_stars = star_icons(s.volume_stars);

    let _ = writeln!(
        out,
        "| **Final Score** | **{}** | **{}/7 Stars** |",
        final_stars, s.stars
    );
    let _ = writeln!(
        out,
        "| Code Health | {} | {}/7 Stars |",
        code_stars, s.code_stars
    );

    if let (Some(pct), Some(st)) = (s.cov_pct, s.cov_stars) {
        let _ = writeln!(
            out,
            "| Test Coverage | {} | {}/7 Stars ({:.1}% churn-weighted) |",
            star_icons(st),
            st,
            pct
        );
    } else {
        out.push_str("| Test Coverage | N/A | No coverage data generated |\n");
    }

    let _ = writeln!(
        out,
        "| System Volume | {} | {}/7 Stars ({} func LOC) |\n",
        vol_stars, s.volume_stars, s.total_loc
    );

    out.push_str("### Risk Profile Distribution\n\n");
    out.push_str("| Risk Tier | Codebase Volume % |\n");
    out.push_str("| :--- | :---: |\n");
    let _ = writeln!(out, "| Moderate Risk | {:.1}% |", s.pct_moderate);
    let _ = writeln!(out, "| High Risk | {:.1}% |", s.pct_high);
    let _ = writeln!(out, "| Very High Risk | {:.1}% |\n", s.pct_very_high);
}

fn render_violations_section(out: &mut String, res: &AnalysisResult, root_dir: &Path) {
    out.push_str("## 🔍 Detailed Guideline Violations\n\n");

    // 1. Volume
    let vol_violators: Vec<&FunctionMetric> = res
        .metrics
        .iter()
        .filter(|m| m.lines_of_code > 15)
        .collect();
    out.push_str("### 1. Unit Size Violations (> 15 LOC)\n\n");
    if vol_violators.is_empty() {
        out.push_str("*No unit size violations detected. ✅*\n\n");
    } else {
        out.push_str("| File | Function | Line | Lines of Code |\n");
        out.push_str("| :--- | :--- | :---: | :---: |\n");
        for m in &vol_violators {
            let rel_path = format_rel_path(&m.file_path, root_dir);
            let _ = writeln!(
                out,
                "| `{}` | `{}` | {} | **{}** |",
                rel_path, m.function_name, m.start_line, m.lines_of_code
            );
        }
        out.push('\n');
    }

    // 2. Complexity
    let comp_violators: Vec<&FunctionMetric> = res
        .metrics
        .iter()
        .filter(|m| m.cyclomatic_complexity > 5)
        .collect();
    out.push_str("### 2. Unit Complexity Violations (> 5 Branches)\n\n");
    if comp_violators.is_empty() {
        out.push_str("*No unit complexity violations detected. ✅*\n\n");
    } else {
        out.push_str("| File | Function | Line | Cyclomatic Complexity |\n");
        out.push_str("| :--- | :--- | :---: | :---: |\n");
        for m in &comp_violators {
            let rel_path = format_rel_path(&m.file_path, root_dir);
            let _ = writeln!(
                out,
                "| `{}` | `{}` | {} | **{}** |",
                rel_path, m.function_name, m.start_line, m.cyclomatic_complexity
            );
        }
        out.push('\n');
    }

    // 3. Parameters
    let param_violators: Vec<&FunctionMetric> = res
        .metrics
        .iter()
        .filter(|m| m.parameter_count > 4)
        .collect();
    out.push_str("### 3. Unit Interface Violations (> 4 Parameters)\n\n");
    if param_violators.is_empty() {
        out.push_str("*No interface parameter violations detected. ✅*\n\n");
    } else {
        out.push_str("| File | Function | Line | Parameter Count |\n");
        out.push_str("| :--- | :--- | :---: | :---: |\n");
        for m in &param_violators {
            let rel_path = format_rel_path(&m.file_path, root_dir);
            let _ = writeln!(
                out,
                "| `{}` | `{}` | {} | **{}** |",
                rel_path, m.function_name, m.start_line, m.parameter_count
            );
        }
        out.push('\n');
    }

    // 4. Duplication
    let _ = writeln!(
        out,
        "### 4. Code Duplication Spans ({:.1}% Total)\n",
        res.dup_res.percentage
    );
    if res.dup_res.blocks.is_empty() {
        out.push_str("*No duplicated code blocks detected. ✅*\n\n");
    } else {
        out.push_str("| File | Line Span | Duplicated Lines |\n");
        out.push_str("| :--- | :---: | :---: |\n");
        for b in &res.dup_res.blocks {
            let rel_path = format_rel_path(&b.file_path, root_dir);
            let span_len = (b.end_line - b.start_line) + 1;
            let _ = writeln!(
                out,
                "| `{}` | L{}-L{} | **{} lines** |",
                rel_path, b.start_line, b.end_line, span_len
            );
        }
        out.push('\n');
    }
}

fn render_hotspots_section(out: &mut String, res: &AnalysisResult, root_dir: &Path) {
    let mut fr = HashMap::new();
    let g = crate::coupling::CouplingGraph::default();
    for m in res.metrics {
        let r = crate::scoring::categorize_risk(m, &g) as usize;
        *fr.entry(m.file_path.clone()).or_insert(0) += r;
    }

    let mut hs: Vec<_> = fr.keys().collect();
    hs.sort_by_key(|k| -((fr.get(*k).unwrap_or(&0) * res.churns.get(*k).unwrap_or(&0)) as isize));
    hs.retain(|k| *fr.get(*k).unwrap_or(&0) > 0 && *res.churns.get(*k).unwrap_or(&0) > 0);

    out.push_str("## ⚡ Hotspots (Risk × Churn Matrix)\n\n");
    if hs.is_empty() {
        out.push_str("*No high-risk / high-churn hotspots detected. ✅*\n\n");
    } else {
        out.push_str(
            "| Priority | File | Risk Points | Git Churn | Test Coverage | Recommendation |\n",
        );
        out.push_str("| :---: | :--- | :---: | :---: | :---: | :--- |\n");
        for (i, p) in hs.iter().take(10).enumerate() {
            let rel = format_rel_path(p, root_dir);
            let r = fr.get(*p).unwrap_or(&0);
            let c = res.churns.get(*p).unwrap_or(&0);
            let cov_str = if let Some(cv) = res.cov {
                if let Some(c_item) = cv.get(*p) {
                    format!("{:.1}%", c_item.percent())
                } else {
                    "N/A".to_string()
                }
            } else {
                "N/A".to_string()
            };

            let rec = if *r > 10 && *c > 5 {
                "🚨 Critical: Immediate modular refactoring and test harness required."
            } else if *r > 5 {
                "⚠️ High: Split long functions and decrease branching complexity."
            } else {
                "ℹ️ Moderate: Monitor churn and increase unit test coverage."
            };

            let _ = writeln!(
                out,
                "| #{} | `{}` | {} | {} commits | {} | {} |",
                i + 1,
                rel,
                r,
                c,
                cov_str,
                rec
            );
        }
        out.push('\n');
    }
}

fn render_architecture_section(out: &mut String, res: &AnalysisResult, root_dir: &Path) {
    out.push_str("## 🏗️ Architecture & Component Balance\n\n");

    let is_bal = super::is_balanced(res.metrics);
    if is_bal {
        out.push_str(
            "- **Component Balance:** All modules are balanced (< 50% codebase share each). ✅\n",
        );
    } else {
        out.push_str(
            "- **Component Balance:** ⚠️ One component exceeds 50% of the entire codebase.\n",
        );
    }

    let cycles = res.graph.detect_cycles();
    if cycles.is_empty() {
        out.push_str("- **Circular Dependencies:** None detected. ✅\n");
    } else {
        let _ = writeln!(
            out,
            "- **Circular Dependencies:** 🚨 {} detected!",
            cycles.len()
        );
        for (i, cycle) in cycles.iter().take(5).enumerate() {
            let chain: Vec<String> = cycle
                .iter()
                .map(|p| format!("`{}`", format_rel_path(p, root_dir)))
                .collect();
            let _ = writeln!(
                out,
                "  - Cycle #{}: {} -> {}",
                i + 1,
                chain.join(" -> "),
                chain[0]
            );
        }
    }
    out.push('\n');
}

fn star_icons(stars: u8) -> String {
    format!(
        "{}{}",
        "★".repeat(stars as usize),
        "☆".repeat((7 - stars) as usize)
    )
}

fn format_rel_path(path: &Path, root_dir: &Path) -> String {
    path.strip_prefix(root_dir)
        .unwrap_or(path)
        .to_string_lossy()
        .replace('\\', "/")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::coverage::Coverage;
    use tempfile::tempdir;

    #[test]
    fn test_render_markdown_empty() {
        let dir = tempdir().unwrap();
        let graph = crate::coupling::CouplingGraph::default();
        let churns = HashMap::new();
        let dup_res = crate::duplication::DuplicationResult::default();
        let score = Score {
            stars: 7,
            code_stars: 7,
            cov_stars: Some(7),
            cov_pct: Some(100.0),
            volume_stars: 7,
            total_loc: 0,
            pct_moderate: 0.0,
            pct_high: 0.0,
            pct_very_high: 0.0,
        };
        let res = AnalysisResult {
            metrics: &[],
            churns: &churns,
            cov: &None,
            score: &score,
            dup_res: &dup_res,
            graph: &graph,
        };

        let md = render_markdown(&res, dir.path());
        assert!(md.contains("# 📊 SIG Maintainability Report"));
        assert!(md.contains("No unit size violations detected. ✅"));
    }

    #[test]
    fn test_render_markdown_with_violations() {
        let dir = tempdir().unwrap();
        let m1 = FunctionMetric {
            file_path: dir.path().join("src/lib.rs"),
            function_name: "complex_fn".to_string(),
            start_line: 10,
            lines_of_code: 50,
            parameter_count: 6,
            cyclomatic_complexity: 8,
        };
        let metrics = vec![m1];
        let mut churns = HashMap::new();
        churns.insert(dir.path().join("src/lib.rs"), 10);
        let mut cov_map = HashMap::new();
        cov_map.insert(
            dir.path().join("src/lib.rs"),
            Coverage { hit: 5, total: 10 },
        );
        let cov = Some(cov_map);
        let mut dup_res = crate::duplication::DuplicationResult::default();
        dup_res.percentage = 5.0;
        dup_res.blocks.push(crate::duplication::DuplicationBlock {
            file_path: dir.path().join("src/lib.rs"),
            start_line: 1,
            end_line: 10,
        });

        let graph = crate::coupling::CouplingGraph::default();
        let score = Score {
            stars: 4,
            code_stars: 4,
            cov_stars: Some(4),
            cov_pct: Some(50.0),
            volume_stars: 7,
            total_loc: 50,
            pct_moderate: 0.0,
            pct_high: 100.0,
            pct_very_high: 0.0,
        };

        let res = AnalysisResult {
            metrics: &metrics,
            churns: &churns,
            cov: &cov,
            score: &score,
            dup_res: &dup_res,
            graph: &graph,
        };

        let md = render_markdown(&res, dir.path());
        assert!(md.contains("`complex_fn`"));
        assert!(md.contains("L1-L10"));
        assert!(md.contains("src/lib.rs"));

        let report_path = generate_markdown_report(&res, dir.path()).unwrap();
        assert!(report_path.exists());
    }
}
